name: openworld_blind_ai
description: Offline assistive object detection app for visually impaired users.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  flutter_tts: ^3.8.5
  onnxruntime: ^1.4.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/models/yolov8n-oiv7.onnx
    - assets/labels/open_images_v7_601.txt